Repository Layr-Labs/eigensdk-rs, pull requests merged in 2025-01, with the labels that each got.

#151 Delete TxManager
  Cargo.lock
  Cargo.toml
  README.md
  crates/chainio/txmanager/Cargo.toml
  crates/chainio/txmanager/README.md
  crates/chainio/txmanager/src/lib.rs
  crates/chainio/txmanager/src/simple_tx_manager.rs
  crates/eigensdk/Cargo.toml
  crates/eigensdk/README.md
  crates/eigensdk/src/lib.rs
  crates/metrics/Cargo.toml
Labels: M-prevent-stale

#243 ci: add workflow to check bindings are up to date
  .github/workflows/bindings.yml
  CHANGELOG.md
  Makefile
  README.md
  crates/utils/src/sdk/contractsregistry.rs
  crates/utils/src/sdk/mockavsservicemanager.rs
  crates/utils/src/sdk/mockerc20.rs
Labels: pipelines

#239 ci: add workflow to enforce updates to the changelog
  .github/workflows/changelog.yml
Labels: pipelines, changelog-ignore

#247 ci: fix check bindings job
  .github/workflows/bindings.yml
  crates/contracts/foundry.toml
Labels: changelog-ignore

#246 fix:rewardsv2 version in readme to 0.5.4
  CHANGELOG.md
  README.md
Labels: changelog-documentation
