Repository Layr-Labs/eigensdk-rs, pull requests merged in 2025-04, with the labels that each got.

#419 chore:alloy bump to 0.13 and MSRV to 1.81
  .github/workflows/integration.yml
  CHANGELOG.md
  Cargo.lock
  Cargo.toml
  clippy.toml
  crates/chainio/clients/avsregistry/src/reader.rs
Labels: changelog-added

#421 chore: remove unused dependency in `eigen-cli`
  Cargo.lock
  crates/eigen-cli/Cargo.toml
Labels: changelog-ignore

#387 docs: BLS Aggregator Service
  Cargo.lock
  Cargo.toml
  Makefile
  crates/services/bls_aggregation/Cargo.toml
  crates/services/bls_aggregation/README.md
  crates/services/bls_aggregation/diagram/sequence-bls.mmd
  crates/services/bls_aggregation/src/lib.rs
Labels: changelog-ignore

#420 chore: use common testing utils in bls_agg_test
  CHANGELOG.md
  crates/chainio/clients/avsregistry/src/reader.rs
  crates/eigen-cli/src/lib.rs
  crates/m2_contracts/anvil/m2_contracts_deployed_anvil_state/state.json
  crates/m2_contracts/script/deployments/core/31337.json
  crates/m2_contracts/script/deployments/mock-avs/31337.json
  crates/operator_sets_contracts/anvil/operatorset_contracts_deployed_anvil_state/state.json
  crates/operator_sets_contracts/mock_avs_config.json
  crates/operator_sets_contracts/script/DeployMockAvs.s.sol
  crates/operator_sets_contracts/script/deployments/core/31337.json
  crates/operator_sets_contracts/script/deployments/mock-avs/31337.json
  crates/operator_sets_contracts/script/utils/MockAvsDeploymentLib.sol
  crates/services/bls_aggregation/src/bls_agg_test.rs
  tests/integration/src/lib.rs
  tests/testing-utils/src/chain_clients.rs
Labels: changelog-added

#426 feat: features aggregator
  Cargo.lock
  crates/aggregator/src/lib.rs
  crates/aggregator/src/traits/task_processor.rs
  crates/eigensdk/Cargo.toml
  crates/eigensdk/src/lib.rs
Labels: changelog-ignore

#422 test: wait for transaction before doing call
  crates/chainio/clients/avsregistry/src/writer.rs
  crates/chainio/clients/elcontracts/src/writer.rs
  tests/testing-utils/src/anvil.rs
Labels: changelog-ignore

#432 refactor: move to tarpc server
  Cargo.lock
  crates/aggregator/Cargo.toml
  crates/aggregator/src/lib.rs
  crates/aggregator/src/rpc_server.rs
Labels: changelog-ignore

#434 feat(v2): add an example of how to use the aggregator
  Cargo.lock
  Cargo.toml
  examples/aggregator/Cargo.toml
  examples/aggregator/examples/aggregator.rs
Labels: changelog-ignore

#409 docs: avs registry service
  crates/services/avsregistry/src/chaincaller.rs
  crates/services/avsregistry/src/lib.rs
Labels: changelog-documentation

#406 docs: operator info service
  crates/services/operatorsinfo/src/lib.rs
  crates/services/operatorsinfo/src/operator_info.rs
Labels: changelog-documentation

#438 docs: fix doc warnings
  crates/chainio/clients/avsregistry/src/writer.rs
  crates/chainio/clients/elcontracts/src/writer.rs
  crates/chainio/clients/fireblocks/src/client.rs
  crates/crypto/bn254/src/utils.rs
  crates/eigen-cli/src/bls.rs
  crates/services/operatorsinfo/src/operatorsinfo_inmemory.rs
  crates/signer/src/web3_signer.rs
  crates/types/src/operator.rs
  tests/testing-utils/src/chain_clients.rs
  tests/testing-utils/src/m2_holesky_constants.rs
  tests/testing-utils/src/mainnet_constants.rs
  tests/testing-utils/src/transaction.rs
Labels: changelog-documentation

#446 chore: merge changes from main branch
  Cargo.lock
  Cargo.toml
  release-plz.toml
Labels: changelog-ignore

#448 ci: add workflow_dispatch for release-plz
  .github/workflows/release-plz.yml
Labels: changelog-ignore

#449 fix: ignore integration tests crate when publishing
  release-plz.toml
Labels: changelog-ignore

#450 fix: use path-only dependency for testing utils
  Cargo.lock
  Cargo.toml
  crates/chainio/clients/avsregistry/Cargo.toml
  crates/chainio/clients/elcontracts/Cargo.toml
  crates/chainio/clients/eth/Cargo.toml
  crates/chainio/clients/eth/src/instrumented_client.rs
  crates/crypto/bls/Cargo.toml
  crates/eigen-cli/Cargo.toml
  crates/metrics/Cargo.toml
  crates/metrics/collectors/economic/Cargo.toml
  crates/services/avsregistry/Cargo.toml
  crates/services/bls_aggregation/Cargo.toml
  crates/services/operatorsinfo/Cargo.toml
  crates/signer/Cargo.toml
  release-plz.toml
  tests/integration/Cargo.toml
Labels: changelog-ignore

#454 fix: specify version for testing-utils at workspace
  Cargo.toml
  crates/chainio/clients/avsregistry/Cargo.toml
  crates/chainio/clients/elcontracts/Cargo.toml
  crates/chainio/clients/eth/Cargo.toml
  crates/crypto/bls/Cargo.toml
  crates/eigen-cli/Cargo.toml
  crates/metrics/Cargo.toml
  crates/metrics/collectors/economic/Cargo.toml
  crates/services/avsregistry/Cargo.toml
  crates/services/bls_aggregation/Cargo.toml
  crates/services/operatorsinfo/Cargo.toml
  crates/signer/Cargo.toml
Labels: changelog-ignore

#456 docs: update release process doc
  CHANGELOG.md
  README.md
  RELEASE.md
  release-plz.toml
Labels: changelog-documentation

#468 refactor: update CHANGELOG for #464
  CHANGELOG.md
  crates/services/avsregistry/src/chaincaller.rs
Labels: changelog-ignore
